//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5_AngularJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int FuncionarioId { get; set; }
        public string Nome { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public string Email { get; set; }
    }
}
